---
title: "GoogleVis"
author: "JackHo"
date: "July 10, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r gv, results='asis'}
# motion chart
library(googleVis)
M <- gvisMotionChart(Fruits, "Fruit", "Year", options=list(width=600,height=400))
# plot(M)
print(M,"chart")

# Geographical chart
G <- gvisGeoChart(Exports, locationvar = "Country", colorvar = "Profit",options=list(width =600, height=400))
# plot(G)
print(G, "chart")
## see options
# df <- data.frame(label=c("US", "GB", "BR"), val1=c(1,3,4), val2=c(23,12,32))
# Line <- gvisLineChart(df, xvar="label", yvar=c("val1","val2"),
#         options=list(title="Hello World", legend="bottom",
#                 titleTextStyle="{color:'red', fontSize:18}",                         
#                 vAxis="{gridlines:{color:'red', count:3}}",
#                 hAxis="{title:'My Label', titleTextStyle:{color:'blue'}}",
#                 series="[{color:'green', targetAxisIndex: 0}, 
#                          {color: 'blue',targetAxisIndex:1}]",
#                 vAxes="[{title:'Value 1 (%)', format:'##,######%'}, 
#                                   {title:'Value 2 (\U00A3)'}]",                          
#                 curveType="function", width=500, height=300                         
#                 ))

# merge googleVis charts
T1 <- gvisTable(Exports, options=list(width = 200, height= 270))
GT <- gvisMerge(G, T1, horizontal = FALSE)
GTM <- gvisMerge(GT, M, horizontal = TRUE, tableOptions="bgcolor=\"#CCCCCC\" cellspacing=10")
# plot(GTM)
print(GTM,"chart")
```

